### ISSUE TITLE
怎么上传图片或者文本文件

### ISSUE THREAD

**Issue by huangzhitian** [GavinGoo/pandora-web#11]
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/1074caae-b210-42e7-8550-e0cda77299b3)
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/d8e521c0-791a-48a9-93e0-1740eb1e21e4)

**Comment by GavinGoo** [comment]
能帮忙看看上传时/backend-api/files接口的响应内容吗？

**Comment by huangzhitian** [comment]
> 能帮忙看看上传时/backend-api/files接口的响应内容吗？

日志没有反应
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/5e6aae46-9a10-4538-b1b7-c01b6b99ff23)

**Comment by GavinGoo** [comment]
> 能帮忙看看上传时/backend-api/files接口的响应内容吗？

是F12开发者工具里 不好意思没说清楚

**Comment by huangzhitian** [comment]
> > 能帮忙看看上传时/backend-api/files接口的响应内容吗？
> 
> 是F12开发者工具里 不好意思没说清楚

![image](https://github.com/GavinGoo/pandora-web/assets/129321746/64cf6d2f-bd40-48e3-935c-0c95e6ae294f)

**Comment by GavinGoo** [comment]
看看响应内容是啥？

**Comment by GavinGoo** [comment]
不对劲。你这个好像是网络问题，响应状态码也没有。试试绕过nginx访问上传呢？

**Comment by huangzhitian** [comment]
> 不对劲。你这个好像是网络问题，响应状态码也没有。试试绕过nginx访问上传呢？

我用宝塔反代绑定的域名，还真是这个问题，这个有解决方法吗？使用IP就能上传了，但是页面不显示图片是一张白板
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/5fab59fa-09d6-4137-a4a9-80c47bd95c82)
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/7221457e-083a-4474-8c14-fbe6307f6617)

**Comment by GavinGoo** [comment]
试试我的nginx配置：
```
location / {
            proxy_http_version 	1.1;
            proxy_pass 		http://IP:端口;
            proxy_set_header	Connection		"";
            proxy_set_header   	Host			$http_host;
            proxy_set_header 	X-Forwarded-Proto 	$scheme;
            proxy_set_header   	X-Real-IP          	$remote_addr;
            proxy_set_header   	X-Forwarded-For    	$proxy_add_x_forwarded_for;
            
            proxy_buffering off;
            proxy_cache off;
            chunked_transfer_encoding on;
            tcp_nopush on;
            tcp_nodelay on;
    		
            send_timeout 600;
            proxy_connect_timeout 600;
            proxy_send_timeout 600;
            proxy_read_timeout 600;
            proxy_headers_hash_max_size 51200;
            proxy_headers_hash_bucket_size 6400;
}
```
宝塔的nginx配置文件目录可能是在：`/www/server/panel/vhost/nginx`

**Comment by huangzhitian** [comment]
> 试试我的nginx配置：
> 
> ```
> location / {
>             proxy_http_version 	1.1;
>             proxy_pass 		http://IP:端口;
>             proxy_set_header	Connection		"";
>             proxy_set_header   	Host			$http_host;
>             proxy_set_header 	X-Forwarded-Proto 	$scheme;
>             proxy_set_header   	X-Real-IP          	$remote_addr;
>             proxy_set_header   	X-Forwarded-For    	$proxy_add_x_forwarded_for;
>             
>             proxy_buffering off;
>             proxy_cache off;
>             chunked_transfer_encoding on;
>             tcp_nopush on;
>             tcp_nodelay on;
>     		
>             send_timeout 600;
>             proxy_connect_timeout 600;
>             proxy_send_timeout 600;
>             proxy_read_timeout 600;
>             proxy_headers_hash_max_size 51200;
>             proxy_headers_hash_bucket_size 6400;
> }
> ```
> 
> 宝塔的nginx配置文件目录可能是在：`/www/server/panel/vhost/nginx`

谢谢大佬我试试
