### ISSUE TITLE
web二次设计

### ISSUE THREAD

**Issue by habacat** [GavinGoo/pandora-web#3]
作者您好，我想问一下，我尝试进行页面的二次开发，包括一些元素和字体的调整。但是我发现页面元素都在压缩过的js中。我应该怎么做才能让这些混淆过的变量变得易读？

感谢您的关注。

![image](https://github.com/GavinGoo/pandora-web/assets/41714213/d64aa11d-f04c-4124-a87c-eb5800cc0b90)

**Comment by GavinGoo** [comment]
你好。我的个人经验是直接在浏览器的`开发者工具`里面找元素源码，因为它可以自动格式化且对性能开销较小。
比如我想把`Explore GPTs`按钮改为`Star on GitHub :)`，先搜索`"Explore GPTs"`定位元素对应的源码所在：
有三个结果，但当我看到此处还有其他侧边栏相关元素时，较为肯定
![微信图片_20240321112738](https://github.com/GavinGoo/pandora-web/assets/30521171/21ec4706-96c9-412c-824f-2372007333a1)
然后通过vsc在源文件搜索关键词`gizmo.exploreStoreEnabled`并修改内容，结果如下：
![微信图片_20240321111811](https://github.com/GavinGoo/pandora-web/assets/30521171/6d9099e9-3247-44f1-9e72-77fbbf2251a3)
> 以上仅是我个人的一点拙见，非唯一之法。祝君顺利

**Comment by habacat** [comment]
谢谢您的帮助
