### ISSUE TITLE
好用，有无赞助链接

### ISSUE THREAD

**Issue by cool-ic** [GavinGoo/pandora-web#5]
好用，有无赞助链接

**Comment by GavinGoo** [comment]
首先非常感谢您的喜欢！！

但以目前的完成度与质量来看，还望您三思

如若您仍愿意赞助，可以请我喝瓶3块钱的茉莉蜜就已经很开心了🥳：

**Comment by cool-ic** [comment]
已经赞助，希望长期维护token登陆 😀

**Comment by GavinGoo** [comment]
感谢！

但是token登录我也是参考其他大佬的方案，由于能力问题没办法保证维护，非常抱歉。。要不您收回赞助吧？🥲

**Comment by cool-ic** [comment]
没事，我现在用着挺好的 😁

**Comment by GavinGoo** [comment]
谢谢大佬，受之有愧了🥲
若您后面想收回赞助，可以随时联系我！

**Comment by GavinGoo** [comment]
大佬可以试试这个可免登使用3.5的[aurora项目](https://github.com/aurora-develop/aurora)，挺不错的

**Comment by waltcow** [comment]
@GavinGoo 留个收款地址，顺便交流交流
