### ISSUE TITLE
请问api模式还能用吗

### ISSUE THREAD

**Issue by huangzhitian** [GavinGoo/pandora-web#9]
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/c3af11c2-4f06-4b5e-b30c-943784f06835)
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/35d108b3-8978-4fab-b24d-52bb03c2fa7e)

**Comment by GavinGoo** [comment]
一直能用的
这个报错应该是你api接口没有返回数据，请问用Postman之类的工具确认过接口可用吗？

**Comment by huangzhitian** [comment]
> 一直能用的 这个报错应该是你api接口没有返回数据，请问用Postman之类的工具确认过接口可用吗？
api接口没问题的，试了coze,gemini,gpt4都是这样的报错，不知道哪里出问题了
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/49bd3ae4-aa04-4b72-9191-c1a425b7641a)
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/6c1ec780-784a-4a63-b576-99933f584f82)

**Comment by GavinGoo** [comment]
如果你要把前端3.5重定向到另一个模型，需要加上环境变量：
PANDORA_GPT35_MODEL=<api.json中模型配置的slug值>

比如你想把gemini-pro作为3.5：
PANDORA_GPT35_MODEL=gemini-pro

**Comment by huangzhitian** [comment]
> 如果你要把前端3.5重定向到另一个模型，需要加上环境变量： PANDORA_GPT35_MODEL=<api.json中模型配置的slug值>
> 
> 比如你想把gemini-pro作为3.5： PANDORA_GPT35_MODEL=gemini-pro

原来如此，gemini-pro能用了，但是试了下coze用不了
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/df2bbae7-f02d-42b5-87a5-0dd6aeee0e01)
![image](https://github.com/GavinGoo/pandora-web/assets/129321746/6db9ae1a-dfaa-49ae-8cf6-b63e236a0321)

**Comment by GavinGoo** [comment]
报了状态码404了呀，确定api是可用的吗？

**Comment by huangzhitian** [comment]
> 报了状态码404了呀，确定api是可用的吗？
在nextchat试了可以

**Comment by GavinGoo** [comment]
麻烦请截图一下api.json的内容看看

**Comment by huangzhitian** [comment]
> 麻烦请截图一下api.json的内容看看

![image](https://github.com/GavinGoo/pandora-web/assets/129321746/fb9342f3-8bf6-447a-a45b-a5842d4bc74c)
我试着把coze改成使用的模型名称也不行

**Comment by GavinGoo** [comment]
只能是api.json里的key值，即模型配置slug的值。
请问coze使用的是https://github.com/deanxv/coze-discord-proxy
这个项目吗？是的话我刚刚测试了一下是没问题的。检查一下cdp的日志以及URL&AUTH？
![Screenshot_20240417_225219_Samsung Internet.jpg](https://github.com/GavinGoo/pandora-web/assets/30521171/64208b19-1081-40fd-9664-7343f1ec41df)

**Comment by huangzhitian** [comment]
> 只能是api.json里的key值，即模型配置slug的值。 请问coze使用的是https://github.com/deanxv/coze-discord-proxy 这个项目吗？是的话我刚刚测试了一下是没问题的。检查一下cdp的日志以及URL&AUTH？ ![Screenshot_20240417_225219_Samsung Internet.jpg](https://private-user-images.githubusercontent.com/30521171/323269643-64208b19-1081-40fd-9664-7343f1ec41df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjY4NzcsIm5iZiI6MTcxMzM2NjU3NywicGF0aCI6Ii8zMDUyMTE3MS8zMjMyNjk2NDMtNjQyMDhiMTktMTA4MS00MGZkLTk2NjQtNzM0M2YxZWM0MWRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNmQ2NjNkNTJkMGE1NjcyMzdhMTg4NWY3MzQ0NDE1NWI3YmM2NDZhZGEyZmVlMWRjNTdjYzc4OTdjMjc3OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B1YXM3VZV_cW6c77ckeHG1qQtNdYXJGn-BZ7fhlI6zc)


是这个项目没错，您方便截图一下api.json我做个参考吗

**Comment by GavinGoo** [comment]
![Clip_2024-04-17_23-27-07](https://github.com/GavinGoo/pandora-web/assets/30521171/402abd8f-4b9e-48e1-8b71-75626c0f1e5f)
比如我想把页面上的3.5模型选项定向到这个模型，配置环境变量：PANDORA_GPT35_MODEL=coze-cdp

噢对了，刚刚我看到您好像修改过回复，说在nextchat正常使用，而我看截图中url的长度 似乎没有路径，会不会是因为nextchat自动给url加了"/v1/chat/completions"呢？

**Comment by huangzhitian** [comment]
> ![Clip_2024-04-17_23-27-07](https://private-user-images.githubusercontent.com/30521171/323285154-402abd8f-4b9e-48e1-8b71-75626c0f1e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjk2MDIsIm5iZiI6MTcxMzM2OTMwMiwicGF0aCI6Ii8zMDUyMTE3MS8zMjMyODUxNTQtNDAyYWJkOGYtNGI5ZS00OGUxLThiNzEtNzU2MjZjMGYxZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1NTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmN2Y5NzM0YjkwNGM0ZjA2NWJmY2U2NjgwMGU3NTExZjAxZmRlZmQ4YzBjNWM5N2Q4OTU5MTYwNTdiMmE0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4lvWJpMR7vye1KK6brygyJBR4P06nukcCnoizof8cfQ) 比如我想把页面上的3.5模型选项定向到这个模型，配置环境变量：PANDORA_GPT35_MODEL=coze-cdp
> 
> 噢对了，刚刚我看到您好像修改过回复，说在nextchat正常使用，而我看截图中url的长度 似乎没有路径，会不会是因为nextchat自动给url加了"/v1/chat/completions"呢？

原来如此，多谢大佬辛苦了

**Comment by GavinGoo** [comment]
我也只是菜鸡，能帮到你就好，不客气
